flags: {}
extra-package-dbs: []
extra-include-dirs: [/usr/local/opt/openssl/include]
packages:
- '.'
- '../trac-to-remarkup'
extra-deps:
- binary-0.8.4.1
- mysql-haskell-0.5.0.0
- wire-streams-0.0.2.0
- word24-1.0.7
- aeson-1.0.2.1
resolver: lts-7.10
compiler-check: newer-minor
